[tool.ruff]
exclude = ["old/"]
line-length = 120

[tool.ruff.lint]
ignore = [
    "D1",
    "D2",
]
select = [
    "D",
    "E",
    "F",
    "Q",
    "W",
]
flake8-quotes.inline-quotes = "single"

[tool.pyrefly]
project-excludes = ["old/"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
