name: Archive update

on:
  schedule:
    - cron: '2 8 * * *'  # 8:02 UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "daily_update"
  cancel-in-progress: false

jobs:
  update-archive:
    name: Update images
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 2

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
          cache: pip

      - name: Install Python dependencies
        working-directory: src
        run: pip install -r requirements.txt

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: src/website/package-lock.json

      - name: Install Node.js dependencies
        working-directory: src/website
        run: npm ci

      - name: Update archive
        working-directory: src
        run: python bing.py
        env:
          CLOUDFLARE_ACCOUNT_ID: '${{ secrets.CLOUDFLARE_ACCOUNT_ID }}'
          CLOUDFLARE_R2_ACCESS_KEY_ID: '${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}'
          CLOUDFLARE_R2_API_TOKEN: '${{ secrets.CLOUDFLARE_R2_API_TOKEN }}'

      - name: Build website
        working-directory: src/website
        run: npm run build

      - name: Update README
        working-directory: src
        run: python update_readme.py
        env:
          CLOUDFLARE_ACCOUNT_ID: '${{ secrets.CLOUDFLARE_ACCOUNT_ID }}'
          CLOUDFLARE_R2_ACCESS_KEY_ID: '${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}'
          CLOUDFLARE_R2_API_TOKEN: '${{ secrets.CLOUDFLARE_R2_API_TOKEN }}'

      - name: Deploy website
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "latest"
          apiToken: ${{ secrets.CLOUDFLARE_WORKERS_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: src/website

      - name: Get previous commit author
        id: previous_commit
        run: echo "PREVIOUS_COMMIT_AUHOUR=$(git log -1 --pretty=%an)" >> "$GITHUB_OUTPUT"

      - name: Commit and push changes (amend previous update)
        if: ${{ steps.previous_commit.outputs.PREVIOUS_COMMIT_AUHOUR == 'GitHub Actions' }}
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Archive update
          commit_user_name: GitHub Actions
          commit_author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
          commit_options: --amend --no-edit
          push_options: --force
          skip_fetch: true

      - name: Commit and push changes
        if: ${{ steps.previous_commit.outputs.PREVIOUS_COMMIT_AUHOUR != 'GitHub Actions' }}
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: Archive update
          commit_user_name: GitHub Actions
          commit_author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
