name: Website build & deployment

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "website"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    name: Build & deploy website
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
          cache: pip

      - name: Install Python dependencies
        working-directory: src
        run: pip install -r requirements.txt

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: src/website/package-lock.json

      - name: Install Node.js dependencies
        working-directory: src/website
        run: npm ci

      # ----------------------------------------------------------------------------------------------------------------

      - name: Build website
        working-directory: src/website
        run: npm run build

      - name: Deploy website
        uses: cloudflare/wrangler-action@v3
        with:
          wranglerVersion: "latest"
          apiToken: ${{ secrets.CLOUDFLARE_WORKERS_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: src/website

      # ----------------------------------------------------------------------------------------------------------------

      - name: Update README
        working-directory: src
        run: python update_readme.py
        env:
          CLOUDFLARE_ACCOUNT_ID: '${{ secrets.CLOUDFLARE_ACCOUNT_ID }}'
          CLOUDFLARE_R2_ACCESS_KEY_ID: '${{ secrets.CLOUDFLARE_R2_ACCESS_KEY_ID }}'
          CLOUDFLARE_R2_API_TOKEN: '${{ secrets.CLOUDFLARE_R2_API_TOKEN }}'

      - name: Commit and push changes
        if: ${{ steps.previous_commit.outputs.PREVIOUS_COMMIT_AUHOUR != 'GitHub Actions' }}
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: README update
          commit_user_name: GitHub Actions
          commit_author: GitHub Actions <41898282+github-actions[bot]@users.noreply.github.com>
          file_pattern: 'README.md'
